// apps/docs/src/components/react/dialog/modal.tsx
import { Dialog } from "@rds/react-dialog";

export function Modal() {
  return (
    <Dialog.Root modal>
      <Dialog.Trigger>Open modal</Dialog.Trigger>
      <Dialog.Content>
        <Dialog.Title>Title</Dialog.Title>
        <p>Hello world modal</p>
        <Dialog.Close>Close</Dialog.Close>
      </Dialog.Content>
    </Dialog.Root>
  );
}

// apps/docs/src/components/angular/dialog/modal.ts
import { Component } from "@angular/core";
import {
  DialogComponent,
  DialogContentComponent,
  DialogTriggerDirective,
  DialogCloseDirective,
  DialogTitleComponent,
} from "@rds/angular-dialog";

@Component({
  selector: "app-dialog-demo",
  standalone: true,
  imports: [
    DialogComponent,
    DialogContentComponent,
    DialogTriggerDirective,
    DialogCloseDirective,
    DialogTitleComponent,
  ],
  template: `
    <rkt-dialog modal="true">
      <button rktDialogTrigger>Open dialog</button>
      <rkt-dialog-content>
        <rkt-dialog-title>Title</rkt-dialog-title>
        <p>Hello world dialog</p>
        <button rktDialogClose>Close</button>
      </rkt-dialog-content>
    </rkt-dialog>
  `,
})
export class Modal {}
